### ISSUE TITLE
Wildcard

### ISSUE THREAD

**Issue by MartinMuzatko** [kgryte/utils-deep-get#1]
Hello!
First of all: thanks for providing this wonderful library!

I was wondering if you have plans on adding wildcards for obtaining object values.

e.g. `deepGet(serverconfig, 'ports.it.*')`
This would return a list of all ports in `ports.*` to iterate through.
As a workaround, I can first do `deepGet(serverconfig, 'ports.it')` and then do `Object.keys()`

Maybe this is not worth to implement, because object keys can also be a '*'.

Please let me know what your thoughts are :)

**Comment by kgryte** [comment]
@MartinMuzatko That is an interesting idea, although one that is probably best implemented as a separate library/package. In the general case where you have `*.*.*....<x>.*`, supporting wildcards would entail a rather different, and more complicated, algorithm. For this particular use case, you may want to use an object "walker" which can traverse an object recursively. This might allow you to get a bit closer to your desired behavior.

Hope that helps!
